"""add invitation id to notifications

Revision ID: b6740794a721
Revises: db62231cd6b3
Create Date: 2026-09-05 12:03:11.663393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6740794a721'
down_revision: Union[str, Sequence[str], None] = 'db62231cd6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('invitation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notifications_invitation_id'), 'notifications', ['invitation_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'organization_invitations', ['invitation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_invitation_id'), table_name='notifications')
    op.drop_column('notifications', 'invitation_id')
    # ### end Alembic commands ###
