"""add task estimated time and checkpoint

Revision ID: e0ebfe1b10f0
Revises: 889937acb98a
Create Date: 2026-09-05 18:38:58.209923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ebfe1b10f0'
down_revision: Union[str, Sequence[str], None] = '889937acb98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_checkpoints_id'), 'task_checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_task_checkpoints_task_id'), 'task_checkpoints', ['task_id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_invited_by'), 'organization_invitations', ['invited_by'], unique=False)
    op.create_index(op.f('ix_organization_invitations_role_id'), 'organization_invitations', ['role_id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_status'), 'organization_invitations', ['status'], unique=False)
    op.add_column('tasks', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'estimated_minutes')
    op.drop_index(op.f('ix_organization_invitations_status'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_role_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_invited_by'), table_name='organization_invitations')
    op.drop_index(op.f('ix_task_checkpoints_task_id'), table_name='task_checkpoints')
    op.drop_index(op.f('ix_task_checkpoints_id'), table_name='task_checkpoints')
    op.drop_table('task_checkpoints')
    # ### end Alembic commands ###
