"""add unique constraint to task title

Revision ID: eac9044a6325
Revises: d2e0f523295f
Create Date: 2026-09-04 12:25:11.658543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac9044a6325'
down_revision: Union[str, Sequence[str], None] = 'd2e0f523295f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_task_project_title', 'tasks', ['project_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_project_title', 'tasks', type_='unique')
    # ### end Alembic commands ###
